services:
  
  
  microservices.server.gateway-1:
    image: microservices.server.gateway
    build:
      context: .
      dockerfile: MicroServices.Server.Gateway/Dockerfile      
    ports:
      - "${GATEWAY_1_PORT}:8080"
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
    #depends_on:
    
    
#  microservices.server.gateway-2:
#    image: microservices.server.gateway
#    build:
#      context: .
#      dockerfile: MicroServices.Server.Gateway/Dockerfile
#    ports:
#      - "${GATEWAY_2_PORT}:8080"
#    environment:
#      "ASPNETCORE_ENVIRONMENT": "Development"
#    #depends_on:
#  
#  microservices.server.gateway-3:
#    image: microservices.server.gateway
#    build:
#      context: .
#      dockerfile: MicroServices.Server.Gateway/Dockerfile
#    ports:
#      - "${GATEWAY_3_PORT}:8080"
#    environment:
#      "ASPNETCORE_ENVIRONMENT": "Development"
#    #depends_on: